#name: Rubocop
#
#on: [push, pull_request]
#
#jobs:
#  rubocop-test:
#    name: Rubocop
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-ruby@v1.45.0
#        with:
#          ruby-version: 2.7
#      - name: Install Dependencies
#        run: gem install bundler
#      - name: Install Gems
#        run: bundle install
#      - name: Install Rubocop
#        run: gem install rubocop-rails && gem install rubocop-performance
#      - name: Check code
#        run: bundle exec rubocop

#name: Rubocop
#
#on: [push, pull_request]
#
#jobs:
#  rubocop-test:
#    name: Rubocop
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-ruby@v1
#        with:
#          ruby-version: 2.7.1
#      - name: Install Rubocop
#        run: gem install rubocop-rails && gem install rubocop-performance
#      - name: Check code
#        run: bundle exec rubocop

name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubocop-
      - name: Install gems
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop --parallel